### ISSUE TITLE
Big Fax make kiwid crash

### ISSUE THREAD

**Issue by lazywalker** [jks-prv/Beagle_SDR_GPS#104]
When I received a big fax picture, say, a 2.5MB png, the kiwid process will crash while that png file beening request, kiwid will restart after a while.

**Comment by jks-prv** [comment]
Yes, that problem is on the bug list. I will try and fix it as soon as I can. Lots going on these days..

**Comment by jks-prv** [comment]
Okay, I think this is fixed in the v1.99 release.
