### ISSUE TITLE
Enhancement: Decoder for DRM Digital Radio Mondiale

### ISSUE THREAD

**Issue by hubertmeier** [jks-prv/Beagle_SDR_GPS#109]
Since the KiwiSDR is a shorrt wave receiver, the decoding of DRM Digital Radio is missing. I don't know if its possible to write a decoder without a license or proprietary software, such a decoder would be nice ...

**Comment by jks-prv** [comment]
This would be very, very difficult. Even if open source code is available (Dream decoder?) where would it run that has enough compute cycles? The Beagle is pretty well saturated. Getting the code run as javascript inside the browser would be a huge challenge.

Someday it might be possible to run Dream as a separate program on the PC running the browser. Then feed it IQ samples from the Kiwi. Currently the Kiwi doesn't supply enough channel bandwidth to do this. This is probably the best way to go.

**Comment by jks-prv** [comment]
This will be fixed in v1.139, at least for using the external Dream application via VAC (virtual audio cable) software. Please see: http://valentfx.com/forums/#/discussion/899/drm-demod-yes-external-app-dream-now-working
