### ISSUE TITLE
SSB carrier frequency selected point!

### ISSUE THREAD

**Issue by lb5va** [jks-prv/Beagle_SDR_GPS#116]
Hello. I really dont understand why this is'nt done for a long time ago. 
When in SSB mode and clicking on a frequency you get the midle of the passband selected, then you have to adjust the carrier point so you can read the station.
The normal way to do this is give the user the carrier point on where you click . Given by the mode setting, USB/LSB, it should present you the correct passband side of the carrier. Understand? 
This is normal setting for all other SDR software I have used, or it can be set this way.
I hope this will be soon impemented. All my users want this. :-)
Stig - LB5VA

**Comment by jks-prv** [comment]
Please check this issue: https://github.com/jks-prv/Beagle_SDR_GPS/issues/5
A some point in the future this alternate behavior will be offered as an option.
