### ISSUE TITLE
Admin Status interface shows only 1 user

### ISSUE THREAD

**Issue by azwirko** [jks-prv/Beagle_SDR_GPS#144]
I'm running v1.156 and on the Admin Status tab I'm only seeing RX0 listed as having one user connected while in all actuality there are 2, 3, or 4 users connected to the SDR if I look at the number of listeners on the Users tab.  

I've tried connecting to the Status page with different browsers, clearing cache and restarting the KiwiSDR server using the Control page and still no change.  The Kick buttons do work on RX1, 2 & 3, even though they don't list and IP address/users. 

Any ideas?

73

andyz - K1RA

![status](https://user-images.githubusercontent.com/12417926/34950091-247d9e92-f9e0-11e7-85c4-fa397c1c4bba.PNG)

![users](https://user-images.githubusercontent.com/12417926/34950021-df98498a-f9df-11e7-9d23-e0550153a203.PNG)

**Comment by jks-prv** [comment]
Hi. Yes, this has been reported a couple of times over on the forum. I have a fix and will include it in today's update.
