### ISSUE TITLE
New WSPR Freqencies

### ISSUE THREAD

**Issue by herrfeuer** [jks-prv/Beagle_SDR_GPS#145]
Hello John,
can you add all WSPR Frequencies as mentioned in the following post: 
http://wsprnet.org/drupal/node/7352
I made some good spots on alternate 80m and 60m frequencies by entering it manually,
but to select it with the drop down menu would be much easier.
The WSPR Bands above 30Mhz could be interesting in combination with a transverter.

kr and vy 73 
fire

**Comment by jks-prv** [comment]
Okay, this will be in the next release.
