### ISSUE TITLE
WSPR Autorun - problem with inactivity timeout

### ISSUE THREAD

**Issue by ON5KQ** [jks-prv/Beagle_SDR_GPS#154]
Nice to have the WSPR Autorun mode implemented.

I found a small problem however:
When using inactivity timer (for example 20min), the IP-adres 127.0.0.1 (the kiwihardware itself) is included and as a consequence the WSPR Autorun mode will end after 20min.
The IP-adres 127.0.0.1 should not be affected by the inactivity timer.

Thanks for implementing it in next update.

Ulli, ON5KQ

**Comment by jks-prv** [comment]
Thanks Ulli. I've tested a fix and will include it in tomorrow's update.
