### ISSUE TITLE
Number of Satellites in GPS Lock decreases with time

### ISSUE THREAD

**Issue by m1geo** [jks-prv/Beagle_SDR_GPS#162]
Hi All

I notice that the number of GPS satellites that are reported on the admin page gradually drops the longer the receiver has been running. If you reboot the SDR, the number returns. I have a good GPS antenna and a clear view of the sky - On a fresh boot, I have 11 or 12 channels with strong RSSI. After an uptime of >230 hours, I notice that this drops to 3 satellites seen. Rebooting fixes this, and I'm back to 11 or 12.

George M1GEO

**Comment by jks-prv** [comment]
Fixed in v1.218
