### ISSUE TITLE
Enhancement: SSTV Decoder

### ISSUE THREAD

**Issue by hubertmeier** [jks-prv/Beagle_SDR_GPS#169]
Hi,

i know, programming a sstv decoder would not be easy but it would be a nice feature ...

Thank you for your hard work

**Comment by PKLoops** [comment]
Hi Hubertmeier,
For SSTV decoding, I use the MMSSTV decoder software loaded on my PC, I have the Chrome Audio patched into it and when using any KiwiSDR, the MMSSTV decoder works really well !
Here is a download link https://hamsoft.ca/pages/mmsstv.php
Cheers
Paul VK3KHZ
