### ISSUE TITLE
Browser and Admin page stops responding

### ISSUE THREAD

**Issue by rrobinett** [jks-prv/Beagle_SDR_GPS#170]
The primary KPH Kiwi73 running v 245 has gone deaf after running for some time.  Web access just hangs.  I can ssh to it and see that kiwid is running, and there is nothing in /var/log/messages, df, or vmstat that suggests an out of resource issue.  Before I restart it from the command line, I could perform diags or make it available for remote ssh access.  Kiwi74/75/... are all running normally.

root@kiwisdr:/var/log# uptime
 02:18:09 up 52 days,  3:33,  1 user,  load average: 1.00, 1.01, 1.05
root@kiwisdr:/var/log# tail messages
Nov 13 08:33:51 kiwisdr kiwid: 11d:02:06:34.804 012.   2   9265.00 kHz  iq z9  "173.73.191.149" Falls Church, Virginia, USA (ARRIVED)
Nov 13 08:34:54 kiwisdr kiwid: 11d:02:07:37.063 012.   2   7321.04 kHz  iq z9  "173.73.191.149" Falls Church, Virginia, USA (LEAVING after 0:01:13)
Nov 13 09:05:47 kiwisdr kiwid: 11d:02:38:30.679 012.   2   7315.00 kHz  iq z9  "173.73.191.149" Arlington, Virginia, USA (ARRIVED)
Nov 13 09:06:14 kiwisdr kiwid: 11d:02:38:57.562 012.   2   9265.00 kHz  iq z9  "173.73.191.149" Arlington, Virginia, USA (LEAVING after 0:00:37)
Nov 13 09:15:19 kiwisdr kiwid: 11d:02:48:02.170 012.   2   9930.00 kHz amn z0  "82.19.160.155" Belper, United Kingdom (ARRIVED)
Nov 13 09:15:32 kiwisdr kiwid: 11d:02:48:15.798 01..   2   9330.00 kHz amn z0  "82.19.160.155" Belper, United Kingdom (LEAVING after 0:00:24)
Nov 13 10:04:23 kiwisdr kiwid: 11d:03:37:06.049 012.   2   4099.43 kHz usb z9  "99.7.173.236" Foster City, California, USA (ARRIVED)
Nov 13 10:22:54 kiwisdr kiwid: 11d:03:55:37.138 01..   2    404.98 kHz  cw z9  "99.7.173.236" Foster City, California, USA (LEAVING after 0:18:42)
Nov 13 10:22:56 kiwisdr kiwid: 11d:03:55:39.172 0...  1    7038.60 kHz usb z13 "73.15.138.50" Hayward, California, USA (LEAVING after 9:12:36)
Nov 13 10:22:56 kiwisdr kiwid: 11d:03:55:40.036 .... 0    14097.10 kHz usb z0  "kiwiwspr_v1.1g" 10.14.70.84 (LEAVING after 111:39:51)
root@kiwisdr:/var/log# df
Filesystem      Size  Used Avail Use% Mounted on
udev             10M     0   10M   0% /dev
tmpfs            99M   13M   87M  13% /run
/dev/mmcblk0p1  3.5G  971M  2.3G  30% /
tmpfs           247M     0  247M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           247M     0  247M   0% /sys/fs/cgroup
root@kiwisdr:/var/log# vmstat 3
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 1  0      0 110740  68484 201104    0    0     0     0    5    2 46 23 31  0  0
 1  0      0 110600  68484 201128    0    0     0     0  265   99 53 47  0  0  0
 1  0      0 110976  68484 201128    0    0     0     0  256   25 52 48  0  0  0
 1  0      0 110880  68484 201128    0    0     0     0  255   26 54 46  0  0  0

**Comment by jks-prv** [comment]
This is likely the bug that was fixed in v1.259/260
