### ISSUE TITLE
Hope to add WFM mode in KIWISDR upgrade software

### ISSUE THREAD

**Issue by longyucheng123** [jks-prv/Beagle_SDR_GPS#225]
If the WFM mode can be added to the kiwisdr software, it will be possible to listen to FM broadcasts (76-108mhz) and aviation bands (118-135.975mhz) from around the world by adding a downconverter extension module

**Comment by DazDSP** [comment]
Your request for WFM mode is not possible.
The system does not have enough bandwidth.
#221 says this.
您无法申请WFM模式。
系统没有足够的带宽。
＃221说这个。
Nín wúfǎ shēnqǐng WFM móshì.
Xìtǒng méiyǒu zúgòu de dàikuān.
#221 Shuō zhège.
