### ISSUE TITLE
Unable to close purple info box on iPhone screen size

### ISSUE THREAD

**Issue by ofadam** [jks-prv/Beagle_SDR_GPS#239]
On an iPhone Xs device using Firefox, the purple "welcome" box can't be retracted after opening. In portrait mode, the close button is hidden at the right and can't be scrolled to. In horizontal mode, the floating bar at the top prevents it from being accessed.

![IMG_7083](https://user-images.githubusercontent.com/5504940/57390719-9b7f2900-7182-11e9-9d4f-a4b7f66f5e35.jpg)
![IMG_7082](https://user-images.githubusercontent.com/5504940/57390720-9b7f2900-7182-11e9-9f78-670809a2757d.jpg)

**Comment by jks-prv** [comment]
That, and some other issues for small-screen devices, will be addressed in today's update (v1.288). See the CHANGE_LOG file.

**Comment by jks-prv** [comment]
Fixed in today's v1.288 release.

**Comment by ofadam** [comment]
Horizontal works perfectly! But portrait orientation still means that the purple box can't be closed.

**Comment by jks-prv** [comment]
Not sure I understand. You mean you can't close it after you first open it? (which is true). It should be closed by default in portrait mode.

**Comment by ofadam** [comment]
It is indeed closed initially – but is impossible to close once opened. I'm not sure there's a good solution, other than taking out a good chunk of text from the introduction, or moving the close button elsewhere.

**Comment by jks-prv** [comment]
Okay, I understand now. I've been working towards a mobile-specific user interface for a long time. But there is a lot of support code required and that's what I'm in the middle of now.
