### ISSUE TITLE
Password field for admin access is visible

### ISSUE THREAD

**Issue by ofadam** [jks-prv/Beagle_SDR_GPS#251]
It looks like v1.290 caused the admin login password to be visible instead of hiding behind asterisks.

**Comment by jks-prv** [comment]
Will be fixed in today's release.

**Comment by ofadam** [comment]
It looks like it's still visible with v1.291?

**Comment by jks-prv** [comment]
Yeah, it's gone bad again. There are caching improvements in v1.290/291 which have helped page load times, but also caused some problems (like this).

**Comment by jks-prv** [comment]
Fixed again (hopefully) in today's v1.292 release.
