### ISSUE TITLE
v1.290: Deleting masked marker crashes kiwid

### ISSUE THREAD

**Issue by RipperFox** [jks-prv/Beagle_SDR_GPS#252]
I just added a masked marker, saw it worked and tried to delete it again.
kiwid crashed:

> Wed Jun 12 08:37:42 00:00:23.734 0... 0      PWD kiwi SND ALLOWED: no config pwd set, allow any
> Wed Jun 12 08:37:49 00:00:29.965 0... 0    L PWD admin config pwd set TRUE, auto-login TRUE
> Wed Jun 12 08:37:49 00:00:29.966 0... 0    L PWD admin ALLOWED: config pwd set, but is_local and auto-login set
> Wed Jun 12 08:37:52 00:00:33.690 0...        DX_UPD [SET DX_UPD g=117 f=-1]
> Wed Jun 12 08:37:52 00:00:33.691 0...        DX_UPD n=2 #117    -1.00 0x0 text=<(null)> notes=<(null)> params=<(null)>
> Wed Jun 12 08:37:52 00:00:33.692 0... 0      DX_UPD 192.168.2.75 delete entry #117
Segmentation fault (core dumped)

Line #**118** of dx.json was the marker in question:
,[3690.00,"LSB","test","",759383,0,{"MK":1}]

**Comment by jks-prv** [comment]
Will be fixed in today's release.
