### ISSUE TITLE
v1.290: With Firefox: Zooming in/out with mousewheel sems jerkier/slower than in 1.289

### ISSUE THREAD

**Issue by RipperFox** [jks-prv/Beagle_SDR_GPS#253]
Observed with FF 67.01 and 67.02: In comparison to v1.289 I have the feeling that zooming with the mouse wheel doesn't work as fluid anymore. It appears that steps are skipped.

Seems somewhat browser specific, since I don't have this problem in Chrome.

**Comment by jks-prv** [comment]
Should be better in v1.291
Mouse wheel should again zoom +- one zoom level per wheel click.
