### ISSUE TITLE
Clicking on frequency in admin status does nothing

### ISSUE THREAD

**Issue by ofadam** [jks-prv/Beagle_SDR_GPS#254]
Although hyperlinked, clicking on the frequencies currently tuned in the admin status doesn't do anything. It looks like it needs a reference other than javascript?

**Comment by PKLoops** [comment]
yeah, agreed, it should fire up an available receiver slot according to the link...

**Comment by jks-prv** [comment]
Fixed recently. Link now appears in admin status tab and opens a new window/tab when clicked.
