### ISSUE TITLE
v1.293 software updates fsk extension not working

### ISSUE THREAD

**Issue by ssanzone** [jks-prv/Beagle_SDR_GPS#260]
Since this update, which was done this morning, my kiwisdr isn't unable to decode fsk any longer. I was decoding 12579.00 KHz, which is a station from my country bringing meteo. After the update, the baud error window remains static. The scope and framing windows shows no data, even when they seem to be running. I'm using the same version of chrome with the new software version that with the previous one, 1.292, wich is Versión 75.0.3770.80 (Build oficial) (64 bits). Any idea what happened?

**Comment by jks-prv** [comment]
Apologies for that. Fixed in v1.294
