### ISSUE TITLE
WSPR extension - 80 m wrong channel

### ISSUE THREAD

**Issue by iw2nke** [jks-prv/Beagle_SDR_GPS#326]
The actual dial frequency of WSPR extension in 80 m band has been set at 3593.5 kHz.
As reported in WSPRnet webpage the right one should be 3568.6 kHz.
Could you correct / update the reference table? 
It is impossible to set the right frequency in case of autorun mode.
73,

Gian Leonardo

**Comment by jks-prv** [comment]
Use "80m_JA". See here: http://valentfx.com/vanilla/discussion/comment/5312
