### ISSUE TITLE
Suggestion, Quickie: SHIFT+CLICK Snap-to for 80m+75m forced to lowest (1kHz not 5kHz)

### ISSUE THREAD

**Issue by HocusLocus** [jks-prv/Beagle_SDR_GPS#328]
SHIFT+CLICK is an invaluable feature for browsing SSB signals by jumping to them quickly and precisely with the mouse ... since modern radios are well calibrated and most conversations happen on the 1kHz boundary, all you need do is SHIFT+CLICK anywhere near the appropriate edge and it is plonk on the freq. Nice!

But in the purple zone (80m+75m) it seems like SHIFT+CLICK is overriding to the 5kHz which is great for other broadcast bands, but mostly amateurs around here, so pls consider forcing 1kHz SHIFT+CLICK snap for 80m+75m.  Thanks!

**Comment by jks-prv** [comment]
In the next release will be the following compromise: If the Kiwi is set to ITU region 2 (Americas) then ham band rounding (1 kHz) will be used in the 3.9 - 4 MHz shared segment.

Shared segments need a complete overhaul. Also, this is yet another thing that should be a "user preference" so you can tailor the rounding to be whatever you want and have it apply to any Kiwi you visit.
