### ISSUE TITLE
WSPR extension "Log decodes to syslog" doesn't seem to work

### ISSUE THREAD

**Issue by ofadam** [jks-prv/Beagle_SDR_GPS#336]
On the WSPR extension page in the admin interface, I have the "log decodes to syslog" turned OFF and I'm still getting them in the log. Is this user error or a bug?
<img width="270" alt="Screen Shot 2019-12-30 at 5 58 10 PM" src="https://user-images.githubusercontent.com/5504940/71605373-ff999780-2b2d-11ea-852b-4b57a1270fd5.png">
<img width="909" alt="Screen Shot 2019-12-30 at 5 58 20 PM" src="https://user-images.githubusercontent.com/5504940/71605374-ff999780-2b2d-11ea-82c5-739a7334f58b.png">

**Comment by jks-prv** [comment]
It should be working correctly. It has to do with the difference between what's recorded to syslog (filesystem) and what's displayed on the admin page log tab. Basically all printf()s in the code are recorded on the log tab, but only some of them are recorded to syslog. The printf() routines have a parameter so you can specify. So when the code is running in the background (as normal) all the messages, including possible debug messages, can be seen in the log, even though they are not filling up the filesystem via syslog.

If you have that switch set to 'No' you should not see WSPR syslog messages when doing an 'msl' (make short log) in the build directory ('cdp' to get there) using the admin console or SSH'd into the Beagle.

**Comment by ofadam** [comment]
Ah, that makes sense – I didn't know that the two log locations were independent.
