### ISSUE TITLE
Still determining local interface address

### ISSUE THREAD

**Issue by ofadam** [jks-prv/Beagle_SDR_GPS#354]
I seem to continuously get the "Still determining local interface address" error message when accessing the admin panel – this has continued for several days and restarts. The Kiwi is perfectly accessible and received an IP address via DHCP; do you know of anything else that would cause this?

**Comment by jks-prv** [comment]
ssh/PuTTY into your Kiwi, "cdp", "msl | tail -500" and email the result to support@kiwisdr.com

**Comment by ofadam** [comment]
Sent.

**Comment by jks-prv** [comment]
Should be fixed. Can re-open if not.
