### ISSUE TITLE
Way to restart WSPR without rebooting?

### ISSUE THREAD

**Issue by ofadam** [jks-prv/Beagle_SDR_GPS#368]
Is there a way to restart WSPR without rebooting the Kiwi? There are times when I want to boot one of the WSPR autorun sessions in favor of another free slot for someone, but would like to start it up again later without needing to do a full reboot. Maybe in terminal?

**Comment by jks-prv** [comment]
Fixed in v1.446. Button appears on admin page, extensions tab (WSPR) when autorun menus changed. All WSPR autorun processes stopped and new ones started according to the new menu settings. Sorry, unchanged entries are also stopped and started. This shouldn't be a big deal.
