### ISSUE TITLE
Found 2 elements with non-unique id #

### ISSUE THREAD

**Issue by narrowfail** [jks-prv/Beagle_SDR_GPS#416]
Hello, minor bug found: Found 2 elements with non-unique id #

`<input id="" class="id-freq-input w3-input w3-border w3-hover-shadow " style="padding:0 4px;max-width:74px" size="8" onkeydown="freqset_keydown(event)" onkeyup="freqset_keyup(this, event)" type="text" value="">
`

`<input id="" class="id-ident-input w3-input w3-border w3-hover-shadow " style="padding:1px" size="20" onkeyup="ident_keyup(this, event)" type="text" value="">`

**Comment by jks-prv** [comment]
Fixed in v1.401
