### ISSUE TITLE
Status Page does not show User count for KiwiSDR setup with all channels passworded

### ISSUE THREAD

**Issue by darksidelemm** [jks-prv/Beagle_SDR_GPS#508]
I run 3x KiwiSDRs, 2 of which are public, and one of which is 'private' (all channels passworded), for members of my Amateur Radio Club (gotta provide some incentive to joint!).

I note that on the 'private' KiwiSDR, the status endpoint (/status) doesn't show the usage status of any of the channels. It just shows:
```
users=0
users_max=0
```
This means I can't monitor the usage of that KiwiSDR alongside the other KiwiSDRs. (And this explains why this particular KiwiSDR appear to have very low usage in my statistics...).
Is it possible to expose this information again? I can understand that not all KiwiSDR operators may want this information exposed, so maybe this needs to be an option?

**Comment by jks-prv** [comment]
Fixed. I'm not going to do a separate release for this single change. But you can get it by forcing a rebuild. Go to the admin page, update tab. Click the "force rebuild" button. Wait 15 minutes or whatever. You can monitor the progress by going to the console tab, connecting and typing the command "m blog" (make build log).
