### ISSUE TITLE
[Bug] Volume cannot be adjusted to 0

### ISSUE THREAD

**Issue by TenkyuChimata** [jks-prv/Beagle_SDR_GPS#595]
Volume cannot be adjusted to 0, 
if you try to set the volume to 0, it will automatically go back to the default position.
I think this problem was introduced in v1.490.
Test SDR: https://sdr.wolfx.jp

https://user-images.githubusercontent.com/34177737/158046860-7c129d9d-4a29-47bc-96c2-4c1c0c6ece70.mp4

**Comment by jks-prv** [comment]
Thank you. Fixed for the next release.
