### ISSUE TITLE
Adding new DX labels with mode NBFM makes kiwisdr stop

### ISSUE THREAD

**Issue by sm3sgp** [jks-prv/Beagle_SDR_GPS#6]
I tried to add a DX Label, shift-click above the frequency scale. If the mode is set to NBFM the kiwsdr stops and does not recover. I can manually edit the /root/kiwi.config/dx.json file, and remove the new entry.

I first thought had to do with with the >30MHz frequency
,[31330.00,"NBFM","Jakt","Local%20hunters"]
But I get the same problem when trying on 20 meters. I think it is connected to the mode NBFM, but not 100% sure.

**Comment by jks-prv** [comment]
Ouch. Yep, that's a bug. Will be fixed in the v1.10 release. Thanks!
