### ISSUE TITLE
LMS denoiser not automatically activated on selection 

### ISSUE THREAD

**Issue by RipperFox** [jks-prv/Beagle_SDR_GPS#621]
The LMS denoiser is not automatically activated when selected from drop down menu.  The user has to open the noise filter parameters to activate the denoiser by the checkbox.

Behaviors seems odd, as other denoiser algorithms get activated by simple selection from the drop down menu.

Tested with v1.518 and FF 100/Edge 101.

Also: Settings of the denoisers aren't saved at all on the client side, right?

**Comment by jks-prv** [comment]
Fixed in v1.521
