### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by loewal** [jks-prv/Beagle_SDR_GPS#638]
Hello,
Could you please update the changelog?
I am running v.1.527, but the latest log is v1.523.

Thank you!

**Comment by jks-prv** [comment]
Explained here: https://forum.kiwisdr.com/index.php?p=/discussion/2620/version-number-1-526#p1
Basically I'm just pushing out versions of development code for the new DSC decoder so I can try it on real signals on as many public Kiwis as possible. I think v1.528 will have a version working well enough that warrants an entry in the change log file.
