### ISSUE TITLE
Tune links broken in version v1.28

### ISSUE THREAD

**Issue by OH1KK** [jks-prv/Beagle_SDR_GPS#70]
Frequencies other users listen are shown as link. Before v1.28 clicking link changed a frequency. On version v1.28 clicking link do not work anymore. On version v1.28 click executes

javascript:tune(3699.00%20kHz%20,'lsb',10);

there is extra %20kHz%20 on link's frequency field which brokes tune function.

**Comment by jks-prv** [comment]
Yes, sorry about that. Something I overlooked during the huge number of changes made in the v1.28 security release. I just fixed it for v1.29
