### ISSUE TITLE
Sqrt fn function broken in version v1.28

### ISSUE THREAD

**Issue by G8JNJ** [jks-prv/Beagle_SDR_GPS#71]
Hi John,

Sorry to report that the Sqrt fn waterfall function broken in version v1.28.

The waterfall background is transparent and you can only see the wallpaper behind it. 

Adjusting Max / Min shows a faint yellow waterfall but it's unusable.

The waterfall is OK if the Sqrt fn is not used.

Regards,

Martin

**Comment by jks-prv** [comment]
fixed in v1.29
