### ISSUE TITLE
/var/log/user.log filling with unresolved URL info

### ISSUE THREAD

**Issue by ka7u** [jks-prv/Beagle_SDR_GPS#75]
Since the v1.28 upgrade the user.log is filling with unresolved URL information. See attached user.zip and search down to v1.28 and below, and ditto on the issues raised by G8JNJ. Also the ability to click a frequency shown in the 4 receiver user menu no longer works.
Ron - KA7U
[user.zip](https://github.com/jks-prv/Beagle_SDR_GPS/files/644891/user.zip)

**Comment by jks-prv** [comment]
All fixed in v1.29 about to go out.
