### ISSUE TITLE
Request for enhancement - Increase Max SSB bandwidth to 10KHz 

### ISSUE THREAD

**Issue by G8JNJ** [jks-prv/Beagle_SDR_GPS#77]
Hi John,

Is it possible to increase the maximum bandwidth in SSB mode to 10KHz.

I note that it's already possible to drag the filter edges to 9KHz for DSB reception.

This is in order to facilitate reception of DRM broadcasts using an external soundcard decoder such as Dream which requires an 9KHz BW USB signal.

https://sourceforge.net/projects/drm/

Thanks,

Martin

**Comment by jks-prv** [comment]
Fixed in v1.139 when using new Kiwi IQ mode to send 10 kHz wide "DSB" IQ data to Dream. Kiwi USB/LSB modes are still restricted to half the max 12 kHz bandwidth (6 kHz).
