### ISSUE TITLE
Unable to compile on Raspberry Pi

### ISSUE THREAD

**Issue by TenkyuChimata** [jks-prv/Beagle_SDR_GPS#791]
When compiling on the Raspberry Pi, the following error appears as shown in the image.

![1](https://github.com/jks-prv/Beagle_SDR_GPS/assets/34177737/054066b6-8ef5-46e6-bb69-b4973ba1205e)

As a temporary solution, comment out "if (gpio_test_pin) gpio_test(gpio_test_pin);" in main.cpp to proceed with the compilation successfully.

This issue might be related to the commit made at https://github.com/jks-prv/Beagle_SDR_GPS/commit/7790869fff1bfa4ebdd4262a317dc38d3be70f79

**Comment by jks-prv** [comment]
Thank you. I committed a change that should fix it.
