### ISSUE TITLE
Blank browser after v1.36 auto install?

### ISSUE THREAD

**Issue by Maddox-zephyr** [jks-prv/Beagle_SDR_GPS#82]
I can no longer get a browser page to access sdr - the page loads fine, it is just blank.  admin page works fine.  Tried on Chrome and IE on a windows 7 machine, and Chrome and Safari on IOS (IPad).

What has changed, I wonder.

**Comment by jks-prv** [comment]
Can you open the Javascript console in the browser and tell us any error messages when the blank page is loaded? On Chrome you do this from the menu item: View > Developer > Javascript Console.
Any errors should be in red text instead of black.

**Comment by jks-prv** [comment]
Also, if your Kiwi is reachable via the Internet (it doesn't have to be publicly listed on sdr.hu) please email support@kiwisdr.com the IP address or domain name and user password (if any) and we'll try it from here. Thanks!

**Comment by Maddox-zephyr** [comment]
Here is the address and it is available via netKiwiSDR serial number: 1389Public IP address (outside your firewall/router): 47.185.229.231Private IP address (inside your firewall/router): 192.168.1.13Netmask: /24KiwiSDR listening on TCP port number: 8073Ethernet MAC address: 7C:66:9D:58:DD:E9On December 28, 2016 at 1:09 PM John Seamons <notifications@github.com> wrote:Also, if your Kiwi is reachable via the Internet (it doesn't have to be publicly listed on sdr.hu) please email support@kiwisdr.com the IP address or domain name and user password (if any) and we'll try it from here. Thanks!—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Maddox-zephyr** [comment]
This is what I see:On December 28, 2016 at 1:04 PM John Seamons <notifications@github.com> wrote:Can you open the Javascript console in the browser and tell us any error messages when the blank page is loaded? On Chrome you do this from the menu item: View > Developer > Javascript Console. Any errors should be in red text instead of black.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Maddox-zephyr** [comment]
Attaching as a file - not sure it worked in line.On December 28, 2016 at 1:04 PM John Seamons <notifications@github.com> wrote:Can you open the Javascript console in the browser and tell us any error messages when the blank page is loaded? On Chrome you do this from the menu item: View > Developer > Javascript Console. Any errors should be in red text instead of black.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by jks-prv** [comment]
I was able to connect and I'm looking at it now. I see what's wrong but I don't understand why it is happening. Let me experiment a little bit..

**Comment by jks-prv** [comment]
Well, this makes no sense. Let's just try a clean build and see if it goes away.
Please login to the Beagle using the root account (no password) using SSH from Linux or PuTTY from Windows. Then type these commands:
"cdp" changes to build directory
"up" stops the server, downloads the latest version from github, rebuilds, installs and re-starts the server
Then try a connection and see how it does.

**Comment by Maddox-zephyr** [comment]
ok - will give it a tryOn December 28, 2016 at 1:50 PM John Seamons <notifications@github.com> wrote:Well, this makes no sense. Let's just try a clean build and see if it goes away. Please login to the Beagle using the root account (no password) using SSH from Linux or PuTTY from Windows. Then type these commands: "cdp" changes to build directory "up" stops the server, downloads the latest version from github, rebuilds, installs and re-starts the server Then try a connection and see how it does.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Maddox-zephyr** [comment]
Compile and restart complete, but no joy on the user interface :-)Here is the log:Wed Dec 28 19:02:52 2016 0:00:00 ....      KiwiSDR v1.36 --------------------------------------------------------------------
Wed Dec 28 19:02:52 2016 0:00:00 ....      compiled: Dec 28 2016 18:58:03
Wed Dec 28 19:02:52 2016 0:00:00 ....      reading configuration from file /root/kiwi.config/kiwi.json: 111 tokens
Wed Dec 28 19:02:52 2016 0:00:00 ....      reading configuration from file /root/kiwi.config/admin.json: 31 tokens
Wed Dec 28 19:02:53 2016 0:00:00 ....      serial number from EEPROM: 1389
Wed Dec 28 19:02:53 2016 0:00:01 ....      reading configuration from file /root/kiwi.config/dx.json: 7052 tokens
Wed Dec 28 19:02:53 2016 0:00:01 ....      883 dx entries
Wed Dec 28 19:02:53 2016 0:00:01 ....      TASK: jmp_buf demangle key 0x02fec0df
Wed Dec 28 19:02:53 2016 0:00:01 ....      listening on port 8073 for "openwebrx"
Wed Dec 28 19:02:53 2016 0:00:01 ....      webserver for "openwebrx" on port [::]:8073
Wed Dec 28 19:02:53 2016 0:00:01 ....      GPIO setup SPI0_CS1 1_19 OUTPUT initial=1
Wed Dec 28 19:02:53 2016 0:00:01 ....       PMUX check GPIO 1_19 P9-16 eeprom 158/0x9e has attr 0x27 <FAST, RX, OE, PD, m7>
Wed Dec 28 19:02:53 2016 0:00:01 ....      GPIO setup GPIO0_30 0_30 BIDIR initial=Z
Wed Dec 28 19:02:53 2016 0:00:01 ....       PMUX check GPIO 0_30 P9-11 eeprom 124/0x7c has attr 0x2f <FAST, RX, PDIS, m7>
Wed Dec 28 19:02:53 2016 0:00:01 ....      GPIO setup GPIO0_31 0_31 BIDIR initial=Z
Wed Dec 28 19:02:53 2016 0:00:01 ....       PMUX check GPIO 0_31 P9-13 eeprom 118/0x76 has attr 0x2f <FAST, RX, PDIS, m7>
Wed Dec 28 19:02:53 2016 0:00:01 ....      GPIO setup GPIO1_16 1_16 BIDIR initial=Z
Wed Dec 28 19:02:53 2016 0:00:01 ....       PMUX check GPIO 1_16 P9-15 eeprom 152/0x98 has attr 0x2f <FAST, RX, PDIS, m7>
Wed Dec 28 19:02:53 2016 0:00:01 ....      GPIO setup GPIO1_17 1_17 BIDIR initial=Z
Wed Dec 28 19:02:53 2016 0:00:01 ....       PMUX check GPIO 1_17 P9-23 eeprom 154/0x9a has attr 0x2f <FAST, RX, PDIS, m7>
Wed Dec 28 19:02:53 2016 0:00:01 ....      GPIO setup GPIO0_15 0_15 BIDIR initial=Z
Wed Dec 28 19:02:53 2016 0:00:01 ....       PMUX check GPIO 0_15 P9-24 eeprom 112/0x70 has attr 0x2f <FAST, RX, PDIS, m7>
Wed Dec 28 19:02:53 2016 0:00:01 ....      GPIO setup GPIO0_14 0_14 BIDIR initial=Z
Wed Dec 28 19:02:53 2016 0:00:01 ....       PMUX check GPIO 0_14 P9-26 eeprom 110/0x6e has attr 0x2f <FAST, RX, PDIS, m7>
Wed Dec 28 19:02:53 2016 0:00:01 ....      GPIO setup JTAG_TCK 2_5 BIDIR initial=Z
Wed Dec 28 19:02:53 2016 0:00:01 ....       PMUX check GPIO 2_5 P8-09 eeprom 172/0xac has attr 0x2f <FAST, RX, PDIS, m7>
Wed Dec 28 19:02:53 2016 0:00:01 ....      GPIO setup JTAG_TMS 2_4 BIDIR initial=Z
Wed Dec 28 19:02:53 2016 0:00:01 ....       PMUX check GPIO 2_4 P8-10 eeprom 174/0xae has attr 0x2f <FAST, RX, PDIS, m7>
Wed Dec 28 19:02:53 2016 0:00:01 ....      GPIO setup JTAG_TDI 2_2 BIDIR initial=Z
Wed Dec 28 19:02:53 2016 0:00:01 ....       PMUX check GPIO 2_2 P8-07 eeprom 170/0xaa has attr 0x2f <FAST, RX, PDIS, m7>
Wed Dec 28 19:02:53 2016 0:00:01 ....      GPIO setup JTAG_TDO 2_3 BIDIR initial=Z
Wed Dec 28 19:02:53 2016 0:00:01 ....       PMUX check GPIO 2_3 P8-08 eeprom 176/0xb0 has attr 0x2f <FAST, RX, PDIS, m7>
Wed Dec 28 19:02:53 2016 0:00:01 ....      GPIO setup P811 1_13 BIDIR initial=Z
Wed Dec 28 19:02:53 2016 0:00:01 ....       PMUX check GPIO 1_13 P8-11 eeprom 146/0x92 has attr 0x2f <FAST, RX, PDIS, m7>
Wed Dec 28 19:02:53 2016 0:00:01 ....      GPIO setup P812 1_12 BIDIR initial=Z
Wed Dec 28 19:02:53 2016 0:00:01 ....       PMUX check GPIO 1_12 P8-12 eeprom 144/0x90 has attr 0x2f <FAST, RX, PDIS, m7>
Wed Dec 28 19:02:53 2016 0:00:01 ....      GPIO setup P813 0_23 BIDIR initial=Z
Wed Dec 28 19:02:53 2016 0:00:01 ....       PMUX check GPIO 0_23 P8-13 eeprom 118/0x76 has attr 0x2f <FAST, RX, PDIS, m7>
Wed Dec 28 19:02:53 2016 0:00:01 ....      GPIO setup P814 0_26 BIDIR initial=Z
Wed Dec 28 19:02:53 2016 0:00:01 ....       PMUX check GPIO 0_26 P8-14 eeprom 120/0x78 has attr 0x2f <FAST, RX, PDIS, m7>
Wed Dec 28 19:02:53 2016 0:00:01 ....      GPIO setup P815 1_15 BIDIR initial=Z
Wed Dec 28 19:02:53 2016 0:00:01 ....       PMUX check GPIO 1_15 P8-15 eeprom 150/0x96 has attr 0x2f <FAST, RX, PDIS, m7>
Wed Dec 28 19:02:53 2016 0:00:01 ....      GPIO setup P816 1_14 BIDIR initial=Z
Wed Dec 28 19:02:53 2016 0:00:01 ....       PMUX check GPIO 1_14 P8-16 eeprom 148/0x94 has attr 0x2f <FAST, RX, PDIS, m7>
Wed Dec 28 19:02:53 2016 0:00:01 ....      GPIO setup P817 0_27 BIDIR initial=Z
Wed Dec 28 19:02:53 2016 0:00:01 ....       PMUX check GPIO 0_27 P8-17 eeprom 122/0x7a has attr 0x2f <FAST, RX, PDIS, m7>
Wed Dec 28 19:02:53 2016 0:00:01 ....      GPIO setup P818 2_1 BIDIR initial=Z
Wed Dec 28 19:02:53 2016 0:00:01 ....       PMUX check GPIO 2_1 P8-18 eeprom 168/0xa8 has attr 0x2f <FAST, RX, PDIS, m7>
Wed Dec 28 19:02:53 2016 0:00:01 ....      GPIO setup P819 0_22 BIDIR initial=Z
Wed Dec 28 19:02:53 2016 0:00:01 ....       PMUX check GPIO 0_22 P8-19 eeprom 116/0x74 has attr 0x2f <FAST, RX, PDIS, m7>
Wed Dec 28 19:02:53 2016 0:00:01 ....      GPIO setup P826 1_29 BIDIR initial=Z
Wed Dec 28 19:02:53 2016 0:00:01 ....       PMUX check GPIO 1_29 P8-26 eeprom 162/0xa2 has attr 0x2f <FAST, RX, PDIS, m7>
Wed Dec 28 19:02:53 2016 0:00:01 ....      GPIO setup FPGA_PGM 1_28 OUTPUT initial=1
Wed Dec 28 19:02:53 2016 0:00:01 ....       PMUX check GPIO 1_28 P9-12 eeprom 160/0xa0 has attr 0x17 <FAST, OE, PU, m7>
Wed Dec 28 19:02:53 2016 0:00:01 ....      GPIO setup FPGA_INIT 1_18 BIDIR initial=Z
Wed Dec 28 19:02:53 2016 0:00:01 ....       PMUX check GPIO 1_18 P9-14 eeprom 156/0x9c has attr 0x37 <FAST, RX, PU, m7>
Wed Dec 28 19:02:53 2016 0:00:01 ....      ### using SPI_DEV
Wed Dec 28 19:02:53 2016 0:00:01 ....      SPIDEV: max_speed 48000000 bpw 32
Wed Dec 28 19:02:54 2016 0:00:02 ....      ping..
Wed Dec 28 19:02:54 2016 0:00:02 ....      load second 1K CPU RAM n=464(232) n+2048=2512(1256)
Wed Dec 28 19:02:54 2016 0:00:02 ....      ping2..
Wed Dec 28 19:02:54 2016 0:00:02 ....      FPGA version 1
Wed Dec 28 19:02:54 2016 0:00:02 ....      ADC_CLOCK: 66.666070 MHz
Wed Dec 28 19:02:54 2016 0:00:02 ....      ext_register: #0 "S_meter"
Wed Dec 28 19:02:54 2016 0:00:02 ....      ext_register: #1 "integrate"
Wed Dec 28 19:02:54 2016 0:00:02 ....      ext_register: #2 "iq_display"
Wed Dec 28 19:02:54 2016 0:00:02 ....      ext_register: #3 "loran_c"
Wed Dec 28 19:02:54 2016 0:00:02 ....      ext_register: #4 "s4285"
Wed Dec 28 19:02:54 2016 0:00:02 ....      ext_register: #5 "test"
Wed Dec 28 19:02:54 2016 0:00:02 ....      ext_register: #6 "wspr"
Wed Dec 28 19:02:54 2016 0:00:02 ....      WSPR frate=9600.5 decim=25.601/26 sps=256 NFFT=512 nbins_411=411
Wed Dec 28 19:02:54 2016 0:00:02 ....      CFG read /root/kiwi.config/admin.json: sdr_hu_register = false
Wed Dec 28 19:02:54 2016 0:00:02 ....      GPS starting..
Wed Dec 28 19:02:54 2016 0:00:02 ....      FFT 65472/16 = 4092 planning..
Wed Dec 28 19:02:55 2016 0:00:03 ....      computing CODE FFT for PRN1
Wed Dec 28 19:02:55 2016 0:00:03 ....      computing CODE FFT for PRN2
Wed Dec 28 19:02:55 2016 0:00:03 ....      computing CODE FFT for PRN3
Wed Dec 28 19:02:55 2016 0:00:03 ....      computing CODE FFT for PRN4
Wed Dec 28 19:02:55 2016 0:00:03 ....      computing CODE FFT for PRN5
Wed Dec 28 19:02:55 2016 0:00:03 ....      computing CODE FFT for PRN6
Wed Dec 28 19:02:55 2016 0:00:03 ....      computing CODE FFT for PRN7
Wed Dec 28 19:02:55 2016 0:00:03 ....      computing CODE FFT for PRN8
Wed Dec 28 19:02:55 2016 0:00:03 ....      computing CODE FFT for PRN9
Wed Dec 28 19:02:55 2016 0:00:03 ....      computing CODE FFT for PRN10
Wed Dec 28 19:02:56 2016 0:00:03 ....      computing CODE FFT for PRN11
Wed Dec 28 19:02:56 2016 0:00:03 ....      computing CODE FFT for PRN12
Wed Dec 28 19:02:56 2016 0:00:04 ....      computing CODE FFT for PRN13
Wed Dec 28 19:02:56 2016 0:00:04 ....      computing CODE FFT for PRN14
Wed Dec 28 19:02:56 2016 0:00:04 ....      computing CODE FFT for PRN15
Wed Dec 28 19:02:56 2016 0:00:04 ....      computing CODE FFT for PRN16
Wed Dec 28 19:02:56 2016 0:00:04 ....      computing CODE FFT for PRN17
Wed Dec 28 19:02:56 2016 0:00:04 ....      computing CODE FFT for PRN18
Wed Dec 28 19:02:56 2016 0:00:04 ....      computing CODE FFT for PRN19
Wed Dec 28 19:02:56 2016 0:00:04 ....      computing CODE FFT for PRN20
Wed Dec 28 19:02:56 2016 0:00:04 ....      computing CODE FFT for PRN21
Wed Dec 28 19:02:56 2016 0:00:04 ....      computing CODE FFT for PRN22
Wed Dec 28 19:02:56 2016 0:00:04 ....      computing CODE FFT for PRN23
Wed Dec 28 19:02:56 2016 0:00:04 ....      computing CODE FFT for PRN24
Wed Dec 28 19:02:56 2016 0:00:04 ....      computing CODE FFT for PRN25
Wed Dec 28 19:02:56 2016 0:00:04 ....      computing CODE FFT for PRN26
Wed Dec 28 19:02:56 2016 0:00:04 ....      computing CODE FFT for PRN27
Wed Dec 28 19:02:57 2016 0:00:04 ....      computing CODE FFT for PRN28
Wed Dec 28 19:02:57 2016 0:00:04 ....      computing CODE FFT for PRN29
Wed Dec 28 19:02:57 2016 0:00:05 ....      computing CODE FFT for PRN30
Wed Dec 28 19:02:57 2016 0:00:05 ....      computing CODE FFT for PRN31
Wed Dec 28 19:02:57 2016 0:00:05 ....      computing CODE FFT for PRN32
Wed Dec 28 19:02:57 2016 0:00:05 ....      (0 users)
Wed Dec 28 19:02:57 2016 0:00:05 ....      UPDATE: scheduled
Wed Dec 28 19:02:57 2016 0:00:05 ....      UPDATE: checking for updates
Wed Dec 28 19:02:58 2016 0:00:06 ....      UPDATE: version 1.36 is current
Wed Dec 28 19:02:58 2016 0:00:06 ....      task update_task:P2:T19 exited by returning
Wed Dec 28 19:03:01 2016 0:00:08 ....      DDNS: private IPv4 <192.168.1.13> 0xc0a8010d /24 0xffffff00
Wed Dec 28 19:03:01 2016 0:00:08 ....      DDNS: private IPv6 LINK-LOCAL <fe80::7e66:9dff:fe58:dde9%eth0> /64 ff:ff:ff:ff:ff:ff:ff:ff:00:00:00:00:00:00:00:00:
Wed Dec 28 19:03:01 2016 0:00:08 ....      DDNS: public ip 47.185.229.231
Wed Dec 28 19:03:01 2016 0:00:08 ....      task dyn_DNS:P2:T02 exited by returning
Wed Dec 28 19:03:02 2016 0:00:10 .... [00] isLocal_IP: flg=0x18 fam=10 socktype=1 proto=6 addrlen=28 ::ffff:192.168.1.16
Wed Dec 28 19:03:02 2016 0:00:10 .... [00] isLocal_IP TRUE IPv4/4_6 remote_ip ::ffff:192.168.1.16 ip_client ::ffff:192.168.1.16/0xc0a80110 ip_server[IPv4] 192.168.1.13/0xc0a8010d nm /24 0xffffff00
Wed Dec 28 19:03:02 2016 0:00:10 .... [00] PWD admin: config pwd set FALSE, auto-login TRUE
Wed Dec 28 19:03:02 2016 0:00:10 .... [00] PWD admin: no config pwd set, but is_local
Wed Dec 28 19:03:02 2016 0:00:10 .... [00] PWD admin allow override: sent from ::ffff:192.168.1.16On December 28, 2016 at 1:50 PM John Seamons <notifications@github.com> wrote:Well, this makes no sense. Let's just try a clean build and see if it goes away. Please login to the Beagle using the root account (no password) using SSH from Linux or PuTTY from Windows. Then type these commands: "cdp" changes to build directory "up" stops the server, downloads the latest version from github, rebuilds, installs and re-starts the server Then try a connection and see how it does.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by jks-prv** [comment]
Okay, I'm really going to have to do some debugging directly on your Kiwi if possible.  Could you open port 22 (SSH) on your firewall/router temporarily? NAT it to the Beagle of course just like port 8073. If there is a root password on the Beagle please email that to support@kiwisdr.com Thanks.

**Comment by Maddox-zephyr** [comment]
I can open 22 and map to the BB. Will email root password when that is done.

**Comment by Maddox-zephyr** [comment]
Port mapped and login emailed

**Comment by jks-prv** [comment]
Okay, bug found and fixed! (on your Kiwi at least, fix will be in v1.37 for everyone else)
You must have uploaded a new or different background photo recently. The photo file was 1.4 MB in size. That's okay, because the limit built-in to the admin page upload command is 2 MB. But what wasn't okay was the 500 kB safety limit on the internal malloc() debug routine. Oops!

Very sorry for the trouble. But glad this bug has been found.

**Comment by Maddox-zephyr** [comment]
thanks!  Didn't think about the photo, just hit upload.What a great remote debug operation...great response.Happy new year!On December 28, 2016 at 4:57 PM John Seamons <notifications@github.com> wrote:Okay, bug found and fixed! (on your Kiwi at least, fix will be in v1.37 for everyone else) You must have uploaded a new or different background photo recently. The photo file was 1.4 MB in size. That's okay, because the limit built-in to the admin page upload command is 2 MB. But what wasn't okay was the 500 kB safety limit on the internal malloc() debug routine. Oops!Very sorry for the trouble. But glad this bug has been found.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
