### ISSUE TITLE
A warn if you forgot to save recording

### ISSUE THREAD

**Issue by Zokalal** [jks-prv/Beagle_SDR_GPS#858]
Make a warning that you forgot to save the recording if you are closing the SDR page.
This will be very useful if you are recording the station, but forget to save the recording of it and accidently closing the page and the recording doesn't get saved.
73

**Comment by jks-prv** [comment]
Unfortunately this cannot be done if you do a client-side close. Such as using the control-W / command-W keys, or the window close button. Server-side terminations, such as the server crashing, or the user connection getting kicked from the various session timeouts do cause the current recording to be saved (but not FAX recording but to more complex issues).

The various browser features such as the "beforeunload" event don't work quite correctly to allow recordings to be saved.
