### ISSUE TITLE
SDR freezes when any of the Contact's links are used

### ISSUE THREAD

**Issue by G8JNJ** [jks-prv/Beagle_SDR_GPS#87]
Hi John,

I've just noticed that the SDR freezes when any of the Contact's links are used.

An F5 or refresh is required to restore operation.

Regards,

Martin - G8JNJ

**Comment by jks-prv** [comment]
This is an issue with how Javascript interacts with "mailto:" URLs. I've tried and as far as I'm aware it cannot be fixed.

**Comment by G8JNJ** [comment]
Hi John,

Ah OK understood.

Not a major problem but worth knowing.

Suggestion - I wonder if cursors or some other marker could be placed on the frequency scale in order to indicate where the other three receivers are tuned to when in use ? That would make it easy to click on them in order to see (and hear) what is being listened to ?

Regards,

Martin - G8JNJ
