### ISSUE TITLE
SNR measurement improvement 

### ISSUE THREAD

**Issue by elektrophysiklk** [jks-prv/Beagle_SDR_GPS#913]
when in the antenna extension the checkbox "Switch to default antenna when no users connected" is enabled the snr measurement is naturally bad 
either the snr measurement is automatically  disabled  when the checkbox is on or the snr measurement switches the default antenna for this period on 

73`s 
Stefan

**Comment by jks-prv** [comment]
Yes, quite right about that. Thanks

**Comment by jks-prv** [comment]
Fixed in v1.696
